export const actions = {
  FETCH_LOG_IN: 'FETCH_LOG_IN',
  FETCH_LOG_IN_DONE: 'FETCH_LOG_IN_DONE',
  FETCH_LOG_IN_FAILED: 'FETCH_LOG_IN_FAILED',
  LOG_OUT: 'LOG_OUT',
  CHANGE_USER_MAIL: 'CHANGE_USER_MAIL',
  CHANGE_USER_PASS: 'CHANGE_USER_PASS'
};
